[package]
name = "temporal-lead-solver"
version = "0.1.0"
edition = "2021"
authors = ["rUv <github.com/ruvnet>"]
description = "Temporal computational lead via sublinear local solvers for diagonally dominant systems"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ruvnet/sublinear-time-solver"
keywords = ["sublinear", "solver", "diagonal-dominance", "temporal", "prediction"]
categories = ["algorithms", "science", "mathematics"]

[lib]
name = "temporal_lead"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "temporal-cli"
path = "src/bin/cli.rs"

[dependencies]
# Core dependencies
ndarray = { version = "0.15", features = ["serde"] }
num-complex = "0.4"
rayon = { version = "1.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"

# Performance optimization
nalgebra = "0.32"
sprs = "0.11"  # Sparse matrix operations

# Timing and benchmarking
criterion = "0.5"
chrono = "0.4"
indicatif = "0.17"

# Mathematical operations
statrs = "0.16"
approx = "0.1"
rand = "0.8"
rand_distr = "0.4"

# Logging
log = "0.4"
env_logger = "0.10"
colored = "2.0"

# Async for network simulations
tokio = { version = "1.35", features = ["full"] }
futures = "0.3"

[dev-dependencies]
proptest = "1.4"
quickcheck = "1.0"
test-case = "3.1"
pretty_assertions = "1.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
inherits = "release"

[features]
default = ["parallel"]
parallel = ["rayon"]
cuda = []  # Future: CUDA support
quantum = []  # Future: Quantum simulation
