[package]
name = "temporal-neural-net"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sublinear = { path = "../" }
nalgebra = "0.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
rand = "0.8"
log = "0.4"
env_logger = "0.10"
chrono = { version = "0.4", features = ["serde"] }
rayon = "1.7"
csv = "1.3"
uuid = { version = "1.0", features = ["v4"] }
tempfile = "3.0"

# WASM dependencies (optional)
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }

[build-dependencies]
chrono = "0.4"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
# statistical = "1.0"  # Not available, we'll implement our own stats
# plotters = "0.3"    # Not needed for basic benchmarks
chrono = { version = "0.4", features = ["serde"] }

[[bench]]
name = "latency_benchmark"
harness = false

[[bench]]
name = "throughput_benchmark"
harness = false

[[bench]]
name = "system_comparison"
harness = false

[[bench]]
name = "statistical_analysis"
harness = false

[[bench]]
name = "simplified_latency_benchmark"
harness = false

[[bench]]
name = "standalone_benchmark"
harness = false

[features]
default = []
simd = []
benchmark = []
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "js-sys", "web-sys", "console_error_panic_hook", "wee_alloc", "getrandom"]
