[package]
name = "temporal-neural-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
rand = "0.8"
chrono = { version = "0.4", features = ["serde"] }
criterion = { version = "0.5", features = ["html_reports"] }

[[bin]]
name = "run_benchmark"
path = "src/main.rs"

[[bin]]
name = "quick_demo"
path = "src/quick_demo.rs"