[package]
name = "real-temporal-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
# Solver integration is now internal

# Core numerical libraries
ndarray = "0.15"
ndarray-rand = "0.14"
nalgebra = "0.32"
rand = "0.8"
rand_distr = "0.4"

# Performance optimization
rayon = "1.7"
num-traits = "0.2"
core_affinity = "0.8"
libc = "0.2"

# CLI
clap = { version = "4.0", features = ["derive"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Timing and benchmarking
criterion = { version = "0.5", optional = true }

[dev-dependencies]
approx = "0.5"
criterion = "0.5"

[features]
default = []
benchmark = ["criterion"]
avx2 = []
avx512 = []
simd = ["avx2"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[[bench]]
name = "optimized_benchmark"
harness = false